services:
  reto2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reto2_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      --ServerApp.root_dir=/app
    working_dir: /app
    environment:
      - JUPYTER_TOKEN=Reto2
    command: 
      - sh
      - -c
      - jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token=Reto2 --ServerApp.password=''



